export const ProductsData = [
    {
      id: 1,
      title: "Mother Asrock X670E Taichi Carrara AM5",
      description: "Plataforma: AMD, Socket: AM5 Ryzen 7000",
      price:"$418.66"     ,
      discountPercentage: 12.96,
      rating: 4.69,
      stock: 94,
      brand: "Apple",
      category: "Amd",
      thumbnail: "https://app.contabilium.com/files/explorer/7026/Productos-Servicios/concepto-9649969.png",
      images: [
        "https://app.contabilium.com/files/explorer/7026/Productos-Servicios/concepto-9649969.png",
      ],
    },
    {
      id: 2,
      title: "Mother ASUS PRIME X670-P",
      description:
        "Plataforma: AMD, Socket: AM5 Ryzen 7000",
      price: "$198.899",
      discountPercentage: 17.94,
      rating: 4.44,
      stock: 34,
      brand: "Apple",
      category: "Amd",
      thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
      images: [
        "https://app.contabilium.com/files/explorer/16752/Productos-Servicios/concepto-9851149.jpg",
      ],
    },
    {
      id: 3,
      title: "Mother MSI B450 Gaming Plus Max AM4",
      description:
        "Plataforma: AMD, Socket: AM4 APU 1th Gen,AM4 APU 2th Gen,AM4 APU 3th Gen,AM4 Ryzen 1th Gen ",
      price: "$70.900",
      discountPercentage: 15.46,
      rating: 4.09,
      stock: 36,
      brand: "Samsung",
      category: "Amd",
      thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
      images: ["https://www.venex.com.ar/products_images/1602345147_product_3_20190716132640_5d2d601054421.png"],
    },
    {
      id: 4,
      title: "Mother Asrock B450 Steel Legend AM4 RGB Dual M.2 Dual USB 3.1",
      description: "Plataforma: AMD, Socket: AM4 APU 1th Gen,AM4 APU 2th Gen,AM4 Ryzen 1th Gen,AM4 Ryzen 2th Gen,AM4 Ryzen 3th Gen",
      price: "$79.899",
      discountPercentage: 17.91,
      rating: 4.3,
      stock: 123,
      brand: "OPPO",
      category: "Amd",
      thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
      images: [
        "https://app.contabilium.com/files/explorer/20302/Productos-Servicios/concepto-4689671.jpg",
      ],
    },
    {
      id: 5,
      title: "Mother ASUS PRIME A520M-K AM4",
      description:
        "Plataforma: AMD, Socket: AM4 Ryzen 3th Gen,AM4 APU 3th Gen,AM4 Ryzen 4th Gen,AM4 APU 5000",
      price: "$54.999",
      discountPercentage: 10.58,
      rating: 4.09,
      stock: 32,
      brand: "Huawei",
      category: "Amd",
      thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
      images: [
        "https://www.maximus.com.ar/Temp/App_WebSite/App_PictureFiles/Items/90MB1500-M0EAY0_800.jpg"
      ],
    },
    {
      id: 6,
      title: "Mother ASUS TUF GAMING Z790-PLUS WIFI DDR4",
      description:"Plataforma: INTEL, Socket: 1700 Alder Lake-S,1700 Raptor Lake",    
      price: "$179.999",
      discountPercentage: 11.02,
      rating: 4.57,
      stock: 83,
      brand: "Apple",
      category: "Intel",
      thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
      images: [
        "https://www.fullh4rd.com.ar/img/productos/Pics_Prod/mother-asus-tuf-gaming-z790plus-wifi-d4-ddr4-s1700-0.jpg",
      ],
    },
    {
      id: 7,
      title: "Mother Asrock B560 Steel Legend S1200",
      description:
        "Plataforma: INTEL, Socket: 1200 Comet Lake,1200 Rocket Lake-S",
      price: "$81.860",
      discountPercentage: 4.15,
      rating: 4.25,
      stock: 50,
      brand: "Samsung",
      category: "Intel",
      thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      images: [
        "https://www.fullh4rd.com.ar/img/productos/Pics_Prod/mother-asrock-b560-steel-legend-ddr4-s1200-0.jpg",
      ],
    },
    {
      id: 8,
      title: "Mother Asrock H610M-HVS LGA 1700",
      description:
        "Plataforma: INTEL, Socket: 1700 Alder Lake-S",
      price: "$52.999",
      discountPercentage: 10.23,
      rating: 4.43,
      stock: 68,
      brand: "Microsoft Surface",
      category: "Intel",
      thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
      images: [
        "https://fullh4rd.com.ar/img/productos/Pics_Prod/mother-asrock-h610mhvs-ddr4-1700-0.jpg",
      ],
    },
    {
      id: 9,
      title: "Mother ASUS PRO H410M-C2 Socket 1200 10th Gen",
      description:
        "Plataforma: INTEL, Socket: 1200 Comet Lake",
      price: "$51.770",
      discountPercentage: 11.83,
      rating: 4.54,
      stock: 96,
      brand: "Infinix",
      category: "Intel",
      thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
      images: [
        "https://images-fe.ssl-images-amazon.com/images/I/61-wZJZVp7L._AC_UL600_SR600,600_.jpg",
      ],
    },
    {
      id: 10,
      title: "Mother ASUS PRIME J4005I-C con Intel Celeron Dual Core on board",
      description:
        "Plataforma: INTEL, Socket: BGA 1090",
      price: "$37.030",
      discountPercentage: 6.18,
      rating: 4.43,
      stock: 89,
      brand: "HP Pavilion",
      category: "Intel",
      thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
      images: [
        "https://www.asus.com/media/global/products/tpDSsY0FgOipo4Xz/P_setting_xxx_0_90_end_692.png",
      ],
    },
    {
      id: 11,
      title: "Notebook Gamer MSI Pulse GL76 FHD 17.3",
      description:
        "Core I7 12700H 16GB 1TB SSD NVMe RTX 3070Q W11 360Hz",
      price: "$1.070.000",
      discountPercentage: 8.4,
      rating: 4.26,
      stock: 65,
      brand: "Impression of Acqua Di Gio",
      category: "Notebooks",
      thumbnail: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
      images: [
        "https://m.media-amazon.com/images/I/71ZYC3eF3LL._AC_UF894,1000_QL80_.jpg",
      ],
    },
    {
      id: 12,
      title: "Notebook Gamer ASUS ROG STRIX G513RM 15.6",
      description: "IPS Ryzen 7 6800H 16GB DDR5 512GB SSD NVMe RTX 3060 W11 Home 165Hz WQHD",
      price: "$921.911",
      discountPercentage: 15.66,
      rating: 4,
      stock: 52,
      brand: "Royal_Mirage",
      category: "Notebooks",
      thumbnail: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
      images: [
        "https://images.fravega.com/f1000/6ee6988c393987533fdcd7ac6df30472.jpg",
      ],
    },
    {
      id: 13,
      title: "Notebook Gamer Aorus 17G FHD 17.3",
      description:
        "Core I7 11800H 16GB (2x8GB) 512GB SSD NVMe RTX 3070 W10H 300Hz",
      price: "$901.180",
      discountPercentage: 8.14,
      rating: 4.59,
      stock: 61,
      brand: "Fog Scent Xpressio",
      category: "Notebooks",
      thumbnail: "https://i.dummyjson.com/data/products/13/thumbnail.webp",
      images: [
        "https://app.contabilium.com/files/explorer/20302/Productos-Servicios/concepto-8330362.jpg",
      ],
    },
    {
      id: 14,
      title: "Notebook Gamer Legion 5 PRO 16",
      description:
        "Ryzen 7 5800H 16GB (2x8GB) 512GB SSD NVMe RTX 3070 W11H 165Hz",
      price: "$879.990",
      discountPercentage: 15.6,
      rating: 4.21,
      stock: 114,
      brand: "Al Munakh",
      category: "Notebooks",
      thumbnail: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
      images: [
        "https://m.media-amazon.com/images/I/71ckj4BDJ+L.jpg",
      ],
    },
    {
      id: 15,
      title: "Notebook Gamer Dell Alienware 15.6",
      description:
        "11800H 16GB 512GB SSD NVMe RTX 3060 W10 144Hz",
      price: "$874.370",
      discountPercentage: 10.99,
      rating: 4.7,
      stock: 105,
      brand: "Lord - Al-Rehab",
      category: "Notebooks",
      thumbnail: "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
      images: [
        "https://static-geektopia.com/storage/t/p/117/117999/800x372/alienware-x15-r1-.jpg",
      ],
    },

  ];